// Code generated by goctl. DO NOT EDIT.
package types

type AddressInfo struct {
	Hash          string  `json:"hash"`
	Label         string  `json:"label"`
	Name          string  `json:"name"`
	Gender        int64   `json:"gender"`
	AddressPhone  string  `json:"addressPhone"`
	PostCode      string  `json:"postCode"`
	Province      string  `json:"province"`
	City          string  `json:"city"`
	Region        string  `json:"region"`
	DetailAddress string  `json:"detailAddress"`
	DetailName    string  `json:"detailName"`
	RoomNumber    string  `json:"roomNumber"`
	Latitude      float64 `json:"latitude"`
	Longitude     float64 `json:"longitude"`
	IsDefault     int64   `json:"isDefault"`
	IsChanged     int     `json:"isChanged"`
}

type UpdateAddressRes struct {
	OpenId          string         `json:"openId"`
	Phone           string         `json:"phone"`
	AddressInfoList []*AddressInfo `json:"addressInfoList"`
}

type UpdateAddressRp struct {
	Address []*AddressInfo `json:"address"`
}

type UpdateAddressResp struct {
	Code string           `json:"code"`
	Msg  string           `json:"msg"`
	Data *UpdateAddressRp `json:"data"`
}

type GetAddressRes struct {
	OpenId string `json:"openId"`
	Phone  string `json:"phone"`
}

type GetAddressRp struct {
	Address []*AddressInfo `json:"address"`
}

type GetAddressResp struct {
	Code string        `json:"code"`
	Msg  string        `json:"msg"`
	Data *GetAddressRp `json:"data"`
}

type ProductInfo struct {
	ProductId       int64   `json:"productId"`
	Amount          int     `json:"amount"`
	Product_title   string  `json:"productTitle"`
	Picture         string  `json:"picture"`
	Status          int     `json:"status"`
	Reserve_time    string  `json:"reserveTime"`
	Sale            int     `json:"sale"`
	Promotion_price float64 `json:"promotionPrice"`
	Original_price  float64 `json:"originalPrice""`
	Cut_price       float64 `json:"cutPrice""`
	Description     string  `json:"description"`
	Unit            string  `json:"unit"`
	Weight          float64 `json:"weight"`
	Attribute       string  `json:"attribute"`
}

type ShoppingCart struct {
	GoodsList []*ProductInfo `json:"goodsList"`
}

type ProductTiny struct {
	PId    int64 `json:"pId"`
	Amount int   `json:"amount"`
}

type UpdateShoppingCartRes struct {
	OpenId         string        `json:"openId"`
	Phone          string        `json:"phone"`
	ShopCartIdList []ProductTiny `json:"shopCartIdList"`
}

type UpdateShoppingCartResp struct {
	Code string        `json:"code"`
	Msg  string        `json:"msg"`
	Data *ShoppingCart `json:"data"`
}

type GetShoppingCartRes struct {
	OpenId string `json:"openId"`
	Phone  string `json:"phone"`
}

type GetShoppingCartResp struct {
	Code string        `json:"code"`
	Msg  string        `json:"msg"`
	Data *ShoppingCart `json:"data"`
}

type RefreshResp struct {
	Code string `json:"code"`
	Msg  string `json:"msg"`
}
