// Code generated by goctl. DO NOT EDIT.
package types

type ResourceInfo struct {
	Algorithm      string `json:"algorithm"`
	Ciphertext     string `json:"ciphertext"`
	AssociatedData string `json:"associated_data"`
	OriginalType   string `json:"original_type"`
	Nonce          string `json:"nonce"`
}

type TellMeSoRes struct {
	Id           string        `json:"id"`
	CreateTime   string        `json:"create_time"`
	EventType    string        `json:"event_type"`
	ResourceType string        `json:"resource_type"`
	Summary      string        `json:"summary"`
	Resource     *ResourceInfo `json:"resource"`
}

type TellMeSoResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type Payerinfo struct {
	Openid string `json:"openid"`
}

type Amountinfo struct {
	Total         int64  `json:"total"`
	PayerTotal    int64  `json:"payer_total"`
	Currency      string `json:"currency"`
	PayerCurrency string `json:"payer_currency"`
}

type SceneInfo struct {
	DeviceId string `json:"device_id"`
}

type Goodsdetail struct {
	GoodsId        string `json:"goods_id"`
	Quantity       int64  `json:"quantity"`
	UnitPrice      int64  `json:"unit_price"`
	DiscountAmount int64  `json:"discount_amount"`
	GoodsRemark    string `json:"goods_remark"`
}

type PromotionDetail struct {
	CouponId            string         `json:"coupon_id"`
	Name                string         `json:"name"`
	Scope               string         `json:"scope"`
	Type                string         `json:"type"`
	Amount              int64          `json:"amount"`
	StockId             string         `json:"stock_id"`
	WechatpayContribute int64          `json:"wechatpay_contribute"`
	MerchantContribute  int64          `json:"merchant_contribute"`
	OtherContribute     int64          `json:"other_contribute"`
	Currency            string         `json:"currency"`
	GoodsDetail         []*Goodsdetail `json:"goods_detail"`
}

type SuccessInfo struct {
	Appid           string             `json:"appid"`
	Mchid           string             `json:"mchid"`
	OutTradeNo      string             `json:"out_trade_no"`
	TransactionId   string             `json:"transaction_id"`
	TradeType       string             `json:"trade_type"`
	TradeState      string             `json:"trade_state"`
	TradeStateDesc  string             `json:"trade_state_desc"`
	BankType        string             `json:"bank_type"`
	Attach          string             `json:"attach"`
	SuccessTime     string             `json:"success_time"`
	Payer           *Payerinfo         `json:"payer"`
	Amount          *Amountinfo        `json:"amount"`
	Sceneinfo       *SceneInfo         `json:"scene_info"`
	Promotiondetail []*PromotionDetail `json:"promotion_detail"`
}

type AddressInfo struct {
	Hash          string  `json:"hash"`
	Label         string  `json:"label"`
	Name          string  `json:"name"`
	Gender        int64   `json:"gender"`
	AddressPhone  string  `json:"addressPhone"`
	PostCode      string  `json:"postCode"`
	Province      string  `json:"province"`
	City          string  `json:"city"`
	Region        string  `json:"region"`
	DetailAddress string  `json:"detailAddress"`
	DetailName    string  `json:"detailName"`
	RoomNumber    string  `json:"roomNumber"`
	Latitude      float64 `json:"latitude"`
	Longitude     float64 `json:"longitude"`
	IsDefault     int64   `json:"isDefault"`
	IsChanged     int     `json:"isChanged"`
}

type UpdateAddressRes struct {
	OpenId          string         `json:"openId"`
	Phone           string         `json:"phone"`
	AddressInfoList []*AddressInfo `json:"addressInfoList"`
}

type UpdateAddressRp struct {
	Address []*AddressInfo `json:"address"`
}

type UpdateAddressResp struct {
	Code string           `json:"code"`
	Msg  string           `json:"msg"`
	Data *UpdateAddressRp `json:"data"`
}

type GetAddressRes struct {
	OpenId string `json:"openId"`
	Phone  string `json:"phone"`
}

type GetAddressRp struct {
	Address []*AddressInfo `json:"address"`
}

type GetAddressResp struct {
	Code string        `json:"code"`
	Msg  string        `json:"msg"`
	Data *GetAddressRp `json:"data"`
}

type ProductInfo struct {
	ProductId       int64   `json:"productId"`
	Amount          int     `json:"amount"`
	Product_title   string  `json:"productTitle"`
	Picture         string  `json:"picture"`
	Status          int     `json:"status"`
	Reserve_time    string  `json:"reserveTime"`
	Sale            int     `json:"sale"`
	Promotion_price float64 `json:"promotionPrice"`
	Original_price  float64 `json:"originalPrice""`
	Cut_price       float64 `json:"cutPrice""`
	Description     string  `json:"description"`
	Unit            string  `json:"unit"`
	Weight          float64 `json:"weight"`
	Attribute       string  `json:"attribute"`
}

type ShoppingCart struct {
	GoodsList []*ProductInfo `json:"goodsList"`
}

type ProductTiny struct {
	PId    int64 `json:"pId"`
	Amount int   `json:"amount"`
}

type UpdateShoppingCartRes struct {
	OpenId         string        `json:"openId"`
	Phone          string        `json:"phone"`
	ShopCartIdList []ProductTiny `json:"shopCartIdList"`
}

type UpdateShoppingCartResp struct {
	Code string        `json:"code"`
	Msg  string        `json:"msg"`
	Data *ShoppingCart `json:"data"`
}

type GetShoppingCartRes struct {
	OpenId string `json:"openId"`
	Phone  string `json:"phone"`
}

type GetShoppingCartResp struct {
	Code string        `json:"code"`
	Msg  string        `json:"msg"`
	Data *ShoppingCart `json:"data"`
}

type RefreshResp struct {
	Code string `json:"code"`
	Msg  string `json:"msg"`
}

type Orderinfo struct {
	Phone           string       `json:"phone"`
	OrderSn         string       `json:"orderSn"`
	CreateTime      string       `json:"createTime"`
	OriginalAmount  float64      `json:"originalAmount"`
	PayAmount       float64      `json:"payAmount"`
	FreightAmount   float64      `json:"freightAmount"`
	OrderStatus     int64        `json:"orderStatus"`
	DeliveryCompany string       `json:"deliveryCompany"`
	DeliverySn      string       `json:"deliverySn"`
	AutoConfirmDay  int64        `json:"autoConfirmDay"`
	Address         *AddressInfo `json:"addressInfo"`
	Note            string       `json:"note"`
	ConfirmStatus   int64        `json:"confirmStatus"`
	DeleteStatus    int64        `json:"deleteStatus"`
	UseIntegration  int64        `json:"useIntegration"`
	PaymentTime     string       `json:"paymentTime"`
}

type NewOrderRes struct {
	OpenId string `json:"openId"`
	Phone  string `json:"phone"`
	Money  int64  `json:"money"`
}

type NewOrderRp struct {
	TimeStamp string `json:"timeStamp"`
	NonceStr  string `json:"nonceStr"`
	Package   string `json:"package"`
	SignType  string `json:"signType"`
	PaySign   string `json:"paySign"`
}

type NewOrderResp struct {
	Code string      `json:"code"`
	Msg  string      `json:"msg"`
	Data *NewOrderRp `json:"data"`
}
