// Code generated by goctl. DO NOT EDIT.
package types

type ResourceInfo struct {
	Algorithm      string `json:"algorithm"`
	Ciphertext     string `json:"ciphertext"`
	AssociatedData string `json:"associated_data"`
	OriginalType   string `json:"original_type"`
	Nonce          string `json:"nonce"`
}

type TellMeSoRes struct {
	Id           string        `json:"id"`
	CreateTime   string        `json:"create_time"`
	EventType    string        `json:"event_type"`
	ResourceType string        `json:"resource_type"`
	Summary      string        `json:"summary"`
	Resource     *ResourceInfo `json:"resource"`
}

type TellMeSoResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type AddressInfo struct {
	Hash          string  `json:"hash"`
	Label         string  `json:"label"`
	Name          string  `json:"name"`
	Gender        int64   `json:"gender"`
	AddressPhone  string  `json:"addressPhone"`
	PostCode      string  `json:"postCode"`
	Province      string  `json:"province"`
	City          string  `json:"city"`
	Region        string  `json:"region"`
	DetailAddress string  `json:"detailAddress"`
	DetailName    string  `json:"detailName"`
	RoomNumber    string  `json:"roomNumber"`
	Latitude      float64 `json:"latitude"`
	Longitude     float64 `json:"longitude"`
	IsDefault     int64   `json:"isDefault"`
}

type UpdateAddressRes struct {
	AddressInfoList []*AddressInfo `json:"addressInfoList"`
}

type UpdateAddressRp struct {
	Address []*AddressInfo `json:"address"`
}

type UpdateAddressResp struct {
	Code string           `json:"code"`
	Msg  string           `json:"msg"`
	Data *UpdateAddressRp `json:"data"`
}

type GetAddressRes struct {
}

type GetAddressRp struct {
	Address []*AddressInfo `json:"address"`
}

type GetAddressResp struct {
	Code string        `json:"code"`
	Msg  string        `json:"msg"`
	Data *GetAddressRp `json:"data"`
}

type GetDefaultAddressRp struct {
	Address *AddressInfo `json:"address"`
}

type GetDefaultAddressResp struct {
	Code string               `json:"code"`
	Msg  string               `json:"msg"`
	Data *GetDefaultAddressRp `json:"data"`
}

type ProductInfo struct {
	ProductId       int64   `json:"productId"`
	Amount          int     `json:"amount"`
	Product_title   string  `json:"productTitle"`
	Picture         string  `json:"picture"`
	Status          int     `json:"status"`
	Reserve_time    string  `json:"reserveTime"`
	Sale            int     `json:"sale"`
	Promotion_price float64 `json:"promotionPrice"`
	Original_price  float64 `json:"originalPrice""`
	Cut_price       float64 `json:"cutPrice""`
	Description     string  `json:"description"`
	Unit            string  `json:"unit"`
	Weight          float64 `json:"weight"`
	Attribute       string  `json:"attribute"`
}

type ShoppingCart struct {
	GoodsList []*ProductTiny `json:"goodsList"`
}

type ProductTiny struct {
	PId    int64 `json:"pId"`
	Amount int   `json:"amount"`
}

type UpdateShoppingCartRes struct {
	ShopCartIdList []*ProductTiny `json:"shopCartIdList"`
}

type UpdateShoppingCartResp struct {
	Code string        `json:"code"`
	Msg  string        `json:"msg"`
	Data *ShoppingCart `json:"data"`
}

type GetShoppingCartRes struct {
}

type GetShoppingCartResp struct {
	Code string        `json:"code"`
	Msg  string        `json:"msg"`
	Data *ShoppingCart `json:"data"`
}

type RefreshResp struct {
	Code string `json:"code"`
	Msg  string `json:"msg"`
}

type PreOrderInfo struct {
	Phone                string         `json:"phone"`
	CreateTime           string         `json:"createTime"`
	PidList              []*ProductTiny `json:"pidList"`
	OriginalAmount       float64        `json:"originalAmount"`
	PointAmount          int64          `json:"pointAmount"`
	ActualAmount         float64        `json:"actualAmount"`
	CouponAmount         float64        `json:"couponAmount"`
	UsedCouponId         int64          `json:"usedCouponId"`
	WeXinPayAmount       float64        `json:"weXinPayAmount"`
	CashAccountPayAmount float64        `json:"cashAccountPayAmount"`
	FreightAmount        float64        `json:"freightAmount"`
}

type OrderInfo struct {
	Phone                string           `json:"phone"`
	OrderSn              string           `json:"orderSn"`
	OutTradeNo           string           `json:"outTradeNo"`
	TransactionId        string           `json:"transactionId"`
	CreateTime           string           `json:"createTime"`
	PidList              []*ProductTiny   `json:"pidList"`
	OriginalAmount       float64          `json:"originalAmount"`
	ProductCutAmount     float64          `json:"productCutAmount"`
	PromotionAmount      float64          `json:"promotionAmount"`
	PointAmount          int64            `json:"pointAmount"`
	ActualAmount         float64          `json:"actualAmount"`
	CouponAmount         float64          `json:"couponAmount"`
	UsedCouponInfo       *CouponStoreInfo `json:"usedCouponInfo"`
	WeXinPayAmount       float64          `json:"weXinPayAmount"`
	CashAccountPayAmount float64          `json:"cashAccountPayAmount"`
	CutPrice             float64          `json:"cutPrice"`
	FreightAmount        float64          `json:"freightAmount"`
	RealFreightAmount    float64          `json:"realFreightAmount"`
	CutFreightAmount     float64          `json:"cutFreightAmount"`
	IfCutFreight         bool             `json:"ifCutFreight"`
	CutPriceWithFreight  float64          `json:"cutPriceWithFreight"`
	Growth               int64            `json:"growth"`
	Address              *AddressInfo     `json:"addressInfo"`
	OrderNote            string           `json:"orderNote"`
	OrderStatus          int64            `json:"orderStatus"`
	DeliveryCompany      string           `json:"deliveryCompany"`
	DeliverySn           string           `json:"deliverySn"`
	ConfirmStatus        int64            `json:"confirmStatus"`
	DeleteStatus         int64            `json:"deleteStatus"`
	PaymentTime          string           `json:"paymentTime"`
	DeliveryTime         string           `json:"deliveryTime"`
	ReceiveTime          string           `json:"receiveTime"`
	ModifyTime           string           `json:"modifyTime"`
	PointsOrder          bool             `json:"pointsOrder"`
}

type Billinfo struct {
	CompanyName    string `json:"companyName"`
	ComponyAddress string `json:"componyAddress"`
	ComponyPhone   string `json:"componyPhone"`
	TaxId          string `json:"taxId"`
	OpeningBank    string `json:"openingBank"`
	BankAccount    string `json:"bankAccount"`
}

type NewOrderRes struct {
	ProductTinyList []*ProductTiny `json:"productTinyList"`
	Address         *AddressInfo   `json:"address"`
	OrderNote       string         `json:"orderNote"` // 订单备注
	UsedCouponId    int64          `json:"usedCouponId"`
	UsedCouponUUID  string         `json:"usedCoupUUID"`
	UseCouponFirst  bool           `json:"useCouponFirst"`
	UseCashFirst    bool           `json:"useCashFirst"`
	UsePointFirst   bool           `json:"usePointFirst"`
}

type NewOrderRp struct {
	OrderInfo    *OrderInfo    `json:"orderInfo"`
	UseWechatPay bool          `json:"useWechatPay"`
	UseAccount   bool          `json:"useAccount"`
	WeiXinPayMsg *WeiXinPayMsg `json:"weiXinPayMsg"`
}

type NewOrderResp struct {
	Code string      `json:"code"`
	Msg  string      `json:"msg"`
	Data *NewOrderRp `json:"data"`
}

type FinishOrderRes struct {
	OrderSn string `json:"orderSn"`
}

type FinishOrderResp struct {
	Code string     `json:"code"`
	Msg  string     `json:"msg"`
	Data *OrderInfo `json:"data"`
}

type PrePayResp struct {
	Code string `json:"code"`
	Msg  string `json:"msg"`
	Data bool   `json:"data"`
}

type BillPayRes struct {
	Money int64 `json:"money"`
}

type BillPayRp struct {
	TimeStamp string `json:"timeStamp"`
	NonceStr  string `json:"nonceStr"`
	Package   string `json:"package"`
	SignType  string `json:"signType"`
	PaySign   string `json:"paySign"`
}

type BillPayResp struct {
	Code string     `json:"code"`
	Msg  string     `json:"msg"`
	Data *BillPayRp `json:"data"`
}

type PreNewOrderRes struct {
	ProductTinyList []*ProductTiny `json:"productTinyList"`
	Address         *AddressInfo   `json:"address"`
	OrderNote       string         `json:"orderNote"` // 订单备注
	UsedCouponId    int64          `json:"usedCouponId"`
	UseCouponFirst  bool           `json:"useCouponFirst"`
	UseCashFirst    bool           `json:"useCashFirst"`
	UsePointFirst   bool           `json:"usePointFirst"`
}

type PreNewOrderRp struct {
	PreOrderInfo *OrderInfo `json:"preOrderInfo"`
}

type PreNewOrderResp struct {
	Code string         `json:"code"`
	Msg  string         `json:"msg"`
	Data *PreNewOrderRp `json:"data"`
}

type GetAllOrderRes struct {
	PageNumber int `json:"pageNumber"`
}

type GetAllOrderRp struct {
	OrderInfos []*OrderInfo `json:"orderInfos"`
}

type GetAllOrderResp struct {
	Code string         `json:"code"`
	Msg  string         `json:"msg"`
	Data *GetAllOrderRp `json:"data"`
}

type GetOrderRes struct {
	OrderSn string `json:"orderSn"`
}

type GetOrderRp struct {
	OrderInfo *OrderInfo `json:"orderInfo"`
}

type GetOrderResp struct {
	Code string      `json:"code"`
	Msg  string      `json:"msg"`
	Data *GetOrderRp `json:"data"`
}

type ChangeOrdeRaddressRes struct {
	OrderSn string       `json:"orderSn"`
	Address *AddressInfo `json:"address"`
}

type ChangeOrdeRaddressRp struct {
	OrderInfo *OrderInfo `json:"orderInfo"`
}

type ChangeOrdeRaddressResp struct {
	Code string                `json:"code"`
	Msg  string                `json:"msg"`
	Data *ChangeOrdeRaddressRp `json:"data"`
}

type CancelOrderRes struct {
	OrderSn string `json:"orderSn"`
}

type CancelOrderRp struct {
	BillNum   float64    `json:"billNum"`
	OrderInfo *OrderInfo `json:"orderInfo"`
}

type CancelOrderResp struct {
	Code string         `json:"code"`
	Msg  string         `json:"msg"`
	Data *CancelOrderRp `json:"data"`
}

type LockMsg struct {
	Phone string `json:"phone"`
	Field string `json:"field"`
}

type GetLockRes struct {
	LockMsgList []*LockMsg `json:"lockMsgList"`
}

type GetLockResp struct {
	Code map[string]bool `json:"code"`
}

type GetPointRes struct {
}

type GetPointRp struct {
	HistoryPoints   int64 `json:"historyPoints"`
	AvailablePoints int64 `json:"availablePoints"`
}

type GetPointResp struct {
	Code string      `json:"code"`
	Msg  string      `json:"msg"`
	Data *GetPointRp `json:"data"`
}

type CashRechargeRes struct {
	Rpid int64 `json:"rpid"`
}

type RechargeOrderInfo struct {
	Phone           string `json:"phone"`
	OrderSn         string `json:"orderSn"`
	OutTradeSn      string `json:"outTradeSn"`
	TransactionId   string `json:"transactionId"`
	CreateOrderTime string `json:"createOrderTime"`
	Rpid            int64  `json:"rpid"`
	Amount          int64  `json:"amount"`
	GiftAmount      int64  `json:"giftAmount"`
	WexinPayAmount  int64  `json:"wexinPayAmount"`
	PaymentTime     string `json:"paymentTime"`
}

type CashRechargeRp struct {
	RechargeOrderInfo *RechargeOrderInfo `json:"rechargeOrderInfo"`
	WeiXinPayMsg      *WeiXinPayMsg      `json:"weiXinPayMsg"`
}

type CashRechargeResp struct {
	Code string          `json:"code"`
	Msg  string          `json:"msg"`
	Data *CashRechargeRp `json:"data"`
}

type ApplyInvoiceRes struct {
	OrderType    int64        `json:"orderType"`
	OrderSn      string       `json:"orderSn"`
	IfDetail     int64        `json:"ifDetail"`
	PostAddress  *AddressInfo `json:"postAddress"`
	InvoinceInfo *InvoiceInfo `json:"invoinceInfo"`
}

type InvoiceInfo struct {
	InvoiceType    int64  `json:"invoiceType"`
	TargetType     int64  `json:"targetType"`
	InvoiceTitle   string `json:"invoiceTitle"`
	ComponyAddress string `json:"componyAddress"`
	ComponyPhone   string `json:"componyPhone"`
	TaxId          string `json:"taxId"`
	OpeningBank    string `json:"openingBank"`
	BankAccount    string `json:"bankAccount"`
}

type InvoiceRp struct {
	Phone        string       `json:"phone"`
	OrderType    int64        `json:"orderType"`
	OrderSn      string       `json:"orderSn"`
	PostAddress  *AddressInfo `json:"postAddress"`
	InvoinceInfo *InvoiceInfo `json:"invoinceInfo"`
	Amount       int64        `json:"amount"`
	IfDetail     int64        `json:"ifDetail"`
	ApplyTime    string       `json:"applyTime"`
	Status       int64        `json:"status"`
	FinishTime   string       `json:"finishTime"`
}

type ApplyInvoiceResp struct {
	Code string     `json:"code"`
	Msg  string     `json:"msg"`
	Data *InvoiceRp `json:"data"`
}

type GetInvoiceRes struct {
	OrderSn string `json:"orderSn"`
}

type GetInvoiceResp struct {
	Code string     `json:"code"`
	Msg  string     `json:"msg"`
	Data *InvoiceRp `json:"data"`
}

type GetAllInvoiceRes struct {
}

type GetAllInvoiceResp struct {
	Code string       `json:"code"`
	Msg  string       `json:"msg"`
	Data []*InvoiceRp `json:"data"`
}

type StarMallOrderRes struct {
	Pid       int64        `json:"pid"`
	Address   *AddressInfo `json:"address"`
	OrderNote string       `json:"orderNote"` // 订单备注
}

type StarMallOrderResp struct {
	Code string     `json:"code"`
	Msg  string     `json:"msg"`
	Data *OrderInfo `json:"data"`
}

type TransactionInit struct {
	Phone           string `json:"phone"`
	OrderSn         string `json:"orderSn"`
	OutTradeSn      string `json:"outTradeSn"`
	NeedCashAccount bool   `json:"needCashAccount"`
	Ammount         int64  `json:"account"`
	TransactionType string `json:"transactionType"`
}

type WeiXinPayMsg struct {
	TimeStamp string `json:"timeStamp"`
	NonceStr  string `json:"nonceStr"`
	Package   string `json:"package"`
	SignType  string `json:"signType"`
	PaySign   string `json:"paySign"`
}

type PayMsg struct {
	WeiXinPayMsg       *WeiXinPayMsg `json:"weiXinPayMsg"`
	NeedWeiXinPay      bool          `json:"neadWeiXinPay"`
	NeedCashAccountPay bool          `json:"neadCashAccountPay"`
	WeiXinPayAmmount   int64         `json:"weiXinPayAmmount"`
	CashPayAmmount     int64         `json:"cashPayAmmount"`
}

type DeletOrderRes struct {
	OrderSn string `json:"orderSn"`
}

type DeletOrderResp struct {
	Code string `json:"code"`
	Msg  string `json:"msg"`
}

type IfOvertimeRes struct {
	OrderSn string `json:"orderSn"`
}

type IfOvertimeResp struct {
}

type CompanyInvoiceInfo struct {
	InvoiceTitle   string `json:"invoiceTitle"`
	ComponyAddress string `json:"componyAddress"`
	ComponyPhone   string `json:"componyPhone"`
	TaxId          string `json:"taxId"`
	OpeningBank    string `json:"openingBank"`
	BankAccount    string `json:"bankAccount"`
	IsDefault      int    `json:"isDefault"`
}

type PersonalInvoiceInfo struct {
	InvoiceTitle string `json:"invoiceTitle"`
	IsDefault    int    `json:"isDefault"`
}

type GetTitleRes struct {
}

type GetTitleRp struct {
	Company  []*CompanyInvoiceInfo  `json:"company"`
	Personal []*PersonalInvoiceInfo `json:"personal"`
}

type GetTitleResp struct {
	Code          string      `json:"code"`
	Msg           string      `json:"msg"`
	TitleInfoList *GetTitleRp `json:"titleInfoList"`
}

type UpdateTitleRes struct {
	TitleInfoList *GetTitleRp `json:"titleInfoList"`
}

type OrderOptionRes struct {
	ProductTinyList []*ProductTiny `json:"productTinyList"`
}

type OrderOptionRp struct {
	OriginalAmount   float64       `json:"originalAmount"`
	PromotionAmount  float64       `json:"promotionAmount"`
	AvailableBalance float64       `json:"availableBalance"`
	AvailableCoupon  []*CouponInfo `json:"availableCoupon"`
}

type OrderOptionResp struct {
	Code string         `json:"code"`
	Msg  string         `json:"msg"`
	Data *OrderOptionRp `json:"data"`
}

type CouponStoreInfo struct {
	CouponId     int64  `json:"couponId"`
	DisabledTime string `json:"disabledTime"`
}

type CouponInfo struct {
	CouponId        int64    `json:"couponId"`
	CouponUUID      string   `json:"couponUUID"`
	EfficientPeriod int64    `json:"efficientPeriod"`
	TypeCode        int64    `json:"typeCode"`
	Type            string   `json:"type"`
	Title           string   `json:"title"`
	LeastConsume    float64  `json:"leastConsume"`
	Cut             float64  `json:"cut"`
	Discount        int64    `json:"discount"`
	DisabledTime    string   `json:"disabledTime"`
	AvailableRange  string   `json:"availableRange"`
	Rules           []string `json:"rules"`
}

type GetSmallCouponRes struct {
}

type GetSmallCouponRp struct {
	CouponInfoList []*CouponInfo `json:"couponInfoList"`
}

type GetSmallCouponResp struct {
	Code string            `json:"code"`
	Msg  string            `json:"msg"`
	Data *GetSmallCouponRp `json:"data"`
}

type StarMallCouponOrderRes struct {
	Cid int64 `json:"cid"`
}

type StarMallCouponOrderResp struct {
	Code string            `json:"code"`
	Msg  string            `json:"msg"`
	Data *GetSmallCouponRp `json:"data"`
}

type GetVoucherRes struct {
	VoucherCode string `json:"voucherCode"`
}

type SuccessMsg struct {
	Success bool `json:"success"`
}

type GetVoucherResp struct {
	Code string      `json:"code"`
	Msg  string      `json:"msg"`
	Data *SuccessMsg `json:"data"`
}

type ScanQRcodeRes struct {
	QRcodeMsg string `json:"qRcodeMsg"`
}

type ScanQRcodeRp struct {
	Type string `json:"type"`
	Msg  string `json:"msg"`
}

type ScanQRcodeResp struct {
	Code string      `json:"code"`
	Msg  string      `json:"msg"`
	Data *SuccessMsg `json:"data"`
}

type GetQrCodeTypeResp struct {
	Code string        `json:"code"`
	Msg  string        `json:"msg"`
	Data *ScanQRcodeRp `json:"data"`
}

type QrCode struct {
	Type       string `json:"type"`
	Parameter1 string `json:"p1"`
	Parameter2 string `json:"p2"`
	Parameter3 string `json:"p3"`
}

type PointLogInfo struct {
	Phone         string  `json:"phone"`
	ChangeAmount  float64 `json:"changeAmount"`
	Behavior      string  `json:"behavior"`
	Balance       float64 `json:"balance"`
	OrderSn       string  `json:"orderSn"`
	OrderType     string  `json:"orderType"`
	OrderDescribe string  `json:"orderDescribe"`
	LogDate       string  `json:"logDate"`
}

type GetPointLogRes struct {
}

type GetPointLogResp struct {
	Code string                     `json:"code"`
	Msg  string                     `json:"msg"`
	Data map[string][]*PointLogInfo `json:"data"`
}
