// Code generated by goctl. DO NOT EDIT!

package cachemodel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	cashAccountFieldNames          = builder.RawFieldNames(&CashAccount{})
	cashAccountRows                = strings.Join(cashAccountFieldNames, ",")
	cashAccountRowsExpectAutoSet   = strings.Join(stringx.Remove(cashAccountFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	cashAccountRowsWithPlaceHolder = strings.Join(stringx.Remove(cashAccountFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"
)

type (
	cashAccountModel interface {
		Insert(ctx context.Context, data *CashAccount) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CashAccount, error)
		FindOneByPhone(ctx context.Context, phone string) (*CashAccount, error)
		Update(ctx context.Context, data *CashAccount) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCashAccountModel struct {
		conn  sqlx.SqlConn
		table string
	}

	CashAccount struct {
		Id      int64  `db:"id"`      // id
		Phone   string `db:"phone"`   // 账号
		Balance int64  `db:"balance"` // 余额
	}
)

func newCashAccountModel(conn sqlx.SqlConn) *defaultCashAccountModel {
	return &defaultCashAccountModel{
		conn:  conn,
		table: "`cash_account`",
	}
}

func (m *defaultCashAccountModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCashAccountModel) FindOne(ctx context.Context, id int64) (*CashAccount, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", cashAccountRows, m.table)
	var resp CashAccount
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCashAccountModel) FindOneByPhone(ctx context.Context, phone string) (*CashAccount, error) {
	var resp CashAccount
	query := fmt.Sprintf("select %s from %s where `phone` = ? limit 1", cashAccountRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, phone)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCashAccountModel) Insert(ctx context.Context, data *CashAccount) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, cashAccountRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Phone, data.Balance)
	return ret, err
}

func (m *defaultCashAccountModel) Update(ctx context.Context, newData *CashAccount) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, cashAccountRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Phone, newData.Balance, newData.Id)
	return err
}

func (m *defaultCashAccountModel) tableName() string {
	return m.table
}
