// Code generated by goctl. DO NOT EDIT!

package cachemodel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userPointsFieldNames          = builder.RawFieldNames(&UserPoints{})
	userPointsRows                = strings.Join(userPointsFieldNames, ",")
	userPointsRowsExpectAutoSet   = strings.Join(stringx.Remove(userPointsFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	userPointsRowsWithPlaceHolder = strings.Join(stringx.Remove(userPointsFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"
)

type (
	userPointsModel interface {
		Insert(ctx context.Context, data *UserPoints) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserPoints, error)
		FindOneByPhone(ctx context.Context, phone string) (*UserPoints, error)
		Update(ctx context.Context, data *UserPoints) error
		Delete(ctx context.Context, id int64) error
		UpdatePoints(ctx context.Context, phone string, points int64) error
	}

	defaultUserPointsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserPoints struct {
		Id              int64  `db:"id"`
		HistoryPoints   int64  `db:"history_points"`   // 历史累计积分
		AvailablePoints int64  `db:"available_points"` // 当前可用积分
		Phone           string `db:"phone"`            // 账号
	}
)

func newUserPointsModel(conn sqlx.SqlConn) *defaultUserPointsModel {
	return &defaultUserPointsModel{
		conn:  conn,
		table: "`user_points`",
	}
}

func (m *defaultUserPointsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserPointsModel) FindOne(ctx context.Context, id int64) (*UserPoints, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userPointsRows, m.table)
	var resp UserPoints
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserPointsModel) FindOneByPhone(ctx context.Context, phone string) (*UserPoints, error) {
	var resp UserPoints
	query := fmt.Sprintf("select %s from %s where `phone` = ? limit 1", userPointsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, phone)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserPointsModel) Insert(ctx context.Context, data *UserPoints) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, userPointsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.HistoryPoints, data.AvailablePoints, data.Phone)
	return ret, err
}

func (m *defaultUserPointsModel) Update(ctx context.Context, newData *UserPoints) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userPointsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.HistoryPoints, newData.AvailablePoints, newData.Phone, newData.Id)
	return err
}

func (m *defaultUserPointsModel) UpdatePoints(ctx context.Context, phone string, points int64) error {
	query := fmt.Sprintf("update %s set `history_points`=`history_points`+?,`available_points`=`available_points`+? where `phone` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, points, points, phone)
	return err
}

func (m *defaultUserPointsModel) tableName() string {
	return m.table
}
