// Code generated by goctl. DO NOT EDIT!

package cachemodel

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userAddressStringFieldNames          = builder.RawFieldNames(&UserAddressString{})
	userAddressStringRows                = strings.Join(userAddressStringFieldNames, ",")
	userAddressStringRowsExpectAutoSet   = strings.Join(stringx.Remove(userAddressStringFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	userAddressStringRowsWithPlaceHolder = strings.Join(stringx.Remove(userAddressStringFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"
)

type (
	userAddressStringModel interface {
		Insert(ctx context.Context, data *UserAddressString) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserAddressString, error)
		FindOneByPhone(ctx context.Context, phone string) (*UserAddressString, error)
		Update(ctx context.Context, data *UserAddressString) error
		Delete(ctx context.Context, id int64) error
		UpdateByPhone(ctx context.Context, newData *UserAddressString) error
	}

	defaultUserAddressStringModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserAddressString struct {
		Id            int64  `db:"id"`
		Phone         string `db:"phone"`
		AddressString string `db:"address_string"`
	}
)

func newUserAddressStringModel(conn sqlx.SqlConn) *defaultUserAddressStringModel {
	return &defaultUserAddressStringModel{
		conn:  conn,
		table: "`user_address_string`",
	}
}

func (m *defaultUserAddressStringModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserAddressStringModel) FindOne(ctx context.Context, id int64) (*UserAddressString, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userAddressStringRows, m.table)
	var resp UserAddressString
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserAddressStringModel) FindOneByPhone(ctx context.Context, phone string) (*UserAddressString, error) {
	var resp UserAddressString
	query := fmt.Sprintf("select %s from %s where `phone` = ? limit 1", userAddressStringRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, phone)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, errors.New("notfind")
	default:
		return nil, err
	}
}

func (m *defaultUserAddressStringModel) Insert(ctx context.Context, data *UserAddressString) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, userAddressStringRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Phone, data.AddressString)
	return ret, err
}

func (m *defaultUserAddressStringModel) Update(ctx context.Context, newData *UserAddressString) error {

	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userAddressStringRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Phone, newData.AddressString, newData.Id)
	return err
}

func (m *defaultUserAddressStringModel) UpdateByPhone(ctx context.Context, newData *UserAddressString) error {

	query := fmt.Sprintf("update %s set `address_string`=? where `phone` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, newData.AddressString, newData.Phone)
	return err
}

func (m *defaultUserAddressStringModel) tableName() string {
	return m.table
}
