// Code generated by goctl. DO NOT EDIT!

package cachemodel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userInvoiceStringFieldNames          = builder.RawFieldNames(&UserInvoiceString{})
	userInvoiceStringRows                = strings.Join(userInvoiceStringFieldNames, ",")
	userInvoiceStringRowsExpectAutoSet   = strings.Join(stringx.Remove(userInvoiceStringFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	userInvoiceStringRowsWithPlaceHolder = strings.Join(stringx.Remove(userInvoiceStringFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"
)

type (
	userInvoiceStringModel interface {
		Insert(ctx context.Context, data *UserInvoiceString) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserInvoiceString, error)
		FindOneByPhone(ctx context.Context, phone string) (*UserInvoiceString, error)
		Update(ctx context.Context, data *UserInvoiceString) error
		Delete(ctx context.Context, id int64) error
		UpdateByPhone(ctx context.Context, newData *UserInvoiceString) error
	}

	defaultUserInvoiceStringModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserInvoiceString struct {
		Id            int64  `db:"id"`
		Phone         string `db:"phone"`          // 用户手机号
		InvoiceString string `db:"invoice_string"` // 发票字符串
	}
)

func newUserInvoiceStringModel(conn sqlx.SqlConn) *defaultUserInvoiceStringModel {
	return &defaultUserInvoiceStringModel{
		conn:  conn,
		table: "`user_invoice_string`",
	}
}

func (m *defaultUserInvoiceStringModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserInvoiceStringModel) FindOne(ctx context.Context, id int64) (*UserInvoiceString, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userInvoiceStringRows, m.table)
	var resp UserInvoiceString
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserInvoiceStringModel) FindOneByPhone(ctx context.Context, phone string) (*UserInvoiceString, error) {
	var resp UserInvoiceString
	query := fmt.Sprintf("select %s from %s where `phone` = ? limit 1", userInvoiceStringRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, phone)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserInvoiceStringModel) Insert(ctx context.Context, data *UserInvoiceString) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, userInvoiceStringRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Phone, data.InvoiceString)
	return ret, err
}

func (m *defaultUserInvoiceStringModel) Update(ctx context.Context, newData *UserInvoiceString) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userInvoiceStringRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Phone, newData.InvoiceString, newData.Id)
	return err
}
func (m *defaultUserInvoiceStringModel) UpdateByPhone(ctx context.Context, newData *UserInvoiceString) error {

	query := fmt.Sprintf("update %s set `invoice_string`=? where `phone` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, newData.InvoiceString, newData.Phone)
	return err
}
func (m *defaultUserInvoiceStringModel) tableName() string {
	return m.table
}
