// Code generated by goctl. DO NOT EDIT!

package cachemodel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userCouponFieldNames          = builder.RawFieldNames(&UserCoupon{})
	userCouponRows                = strings.Join(userCouponFieldNames, ",")
	userCouponRowsExpectAutoSet   = strings.Join(stringx.Remove(userCouponFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	userCouponRowsWithPlaceHolder = strings.Join(stringx.Remove(userCouponFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"
)

type (
	userCouponModel interface {
		Insert(ctx context.Context, data *UserCoupon) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserCoupon, error)
		FindOneByPhone(ctx context.Context, phone string) (*UserCoupon, error)
		Update(ctx context.Context, data *UserCoupon) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserCouponModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserCoupon struct {
		Id          int64  `db:"id"`
		CouponIdMap string `db:"coupon_id_map"` // 优惠券字典{cuuid:{cid:1,disabledtime:}},后领取的靠前排列
		Phone       string `db:"phone"`         // 领取人账号
	}
)

func newUserCouponModel(conn sqlx.SqlConn) *defaultUserCouponModel {
	return &defaultUserCouponModel{
		conn:  conn,
		table: "`user_coupon`",
	}
}

func (m *defaultUserCouponModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}
func (m *defaultUserCouponModel) FindOne(ctx context.Context, id int64) (*UserCoupon, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userCouponRows, m.table)
	var resp UserCoupon
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserCouponModel) FindOneByPhone(ctx context.Context, phone string) (*UserCoupon, error) {
	var resp UserCoupon
	query := fmt.Sprintf("select %s from %s where `phone` = ? limit 1", userCouponRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, phone)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserCouponModel) Insert(ctx context.Context, data *UserCoupon) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, userCouponRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.CouponIdMap, data.Phone)
	return ret, err
}

func (m *defaultUserCouponModel) Update(ctx context.Context, newData *UserCoupon) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userCouponRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.CouponIdMap, newData.Phone, newData.Id)
	return err
}

func (m *defaultUserCouponModel) tableName() string {
	return m.table
}
