// Code generated by goctl. DO NOT EDIT!

package cachemodel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userShoppingCartFieldNames          = builder.RawFieldNames(&UserShoppingCart{})
	userShoppingCartRows                = strings.Join(userShoppingCartFieldNames, ",")
	userShoppingCartRowsExpectAutoSet   = strings.Join(stringx.Remove(userShoppingCartFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	userShoppingCartRowsWithPlaceHolder = strings.Join(stringx.Remove(userShoppingCartFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"

	cacheDevUserShoppingCartIdPrefix    = "cache:dev:userShoppingCart:id:"
	cacheDevUserShoppingCartPhonePrefix = "cache:dev:userShoppingCart:phone:"
)

type (
	userShoppingCartModel interface {
		Insert(ctx context.Context, data *UserShoppingCart) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserShoppingCart, error)
		FindOneByPhone(ctx context.Context, phone string) (*UserShoppingCart, error)
		Update(ctx context.Context, data *UserShoppingCart) error
		Delete(ctx context.Context, id int64) error
		UpdateByPhone(ctx context.Context, phone, shoppingCart string) error
	}

	defaultUserShoppingCartModel struct {
		sqlc.CachedConn
		table string
	}

	UserShoppingCart struct {
		Id           int64  `db:"id"`
		Phone        string `db:"phone"`
		ShoppingCart string `db:"shopping_cart"`
	}
)

func newUserShoppingCartModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultUserShoppingCartModel {
	return &defaultUserShoppingCartModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`user_shopping_cart`",
	}
}

func (m *defaultUserShoppingCartModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	devUserShoppingCartIdKey := fmt.Sprintf("%s%v", cacheDevUserShoppingCartIdPrefix, id)
	devUserShoppingCartPhoneKey := fmt.Sprintf("%s%v", cacheDevUserShoppingCartPhonePrefix, data.Phone)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, devUserShoppingCartIdKey, devUserShoppingCartPhoneKey)
	return err
}

func (m *defaultUserShoppingCartModel) FindOne(ctx context.Context, id int64) (*UserShoppingCart, error) {
	devUserShoppingCartIdKey := fmt.Sprintf("%s%v", cacheDevUserShoppingCartIdPrefix, id)
	var resp UserShoppingCart
	err := m.QueryRowCtx(ctx, &resp, devUserShoppingCartIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userShoppingCartRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserShoppingCartModel) FindOneByPhone(ctx context.Context, phone string) (*UserShoppingCart, error) {
	devUserShoppingCartPhoneKey := fmt.Sprintf("%s%v", cacheDevUserShoppingCartPhonePrefix, phone)
	var resp UserShoppingCart
	err := m.QueryRowIndexCtx(ctx, &resp, devUserShoppingCartPhoneKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `phone` = ? limit 1", userShoppingCartRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, phone); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserShoppingCartModel) Insert(ctx context.Context, data *UserShoppingCart) (sql.Result, error) {
	devUserShoppingCartIdKey := fmt.Sprintf("%s%v", cacheDevUserShoppingCartIdPrefix, data.Id)
	devUserShoppingCartPhoneKey := fmt.Sprintf("%s%v", cacheDevUserShoppingCartPhonePrefix, data.Phone)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, userShoppingCartRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Phone, data.ShoppingCart)
	}, devUserShoppingCartIdKey, devUserShoppingCartPhoneKey)
	return ret, err
}

func (m *defaultUserShoppingCartModel) Update(ctx context.Context, newData *UserShoppingCart) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	devUserShoppingCartIdKey := fmt.Sprintf("%s%v", cacheDevUserShoppingCartIdPrefix, data.Id)
	devUserShoppingCartPhoneKey := fmt.Sprintf("%s%v", cacheDevUserShoppingCartPhonePrefix, data.Phone)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userShoppingCartRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Phone, newData.ShoppingCart, newData.Id)
	}, devUserShoppingCartIdKey, devUserShoppingCartPhoneKey)
	return err
}

func (m *defaultUserShoppingCartModel) UpdateByPhone(ctx context.Context, phone, shoppingCart string) error {
	data, err := m.FindOneByPhone(ctx, phone)
	if err != nil {
		return err
	}
	devUserShoppingCartIdKey := fmt.Sprintf("%s%v", cacheDevUserShoppingCartIdPrefix, data.Id)
	devUserShoppingCartPhoneKey := fmt.Sprintf("%s%v", cacheDevUserShoppingCartPhonePrefix, data.Phone)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `phone` = ?", m.table, userShoppingCartRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, phone, shoppingCart, phone)
	}, devUserShoppingCartIdKey, devUserShoppingCartPhoneKey)
	return err
}

func (m *defaultUserShoppingCartModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheDevUserShoppingCartIdPrefix, primary)
}

func (m *defaultUserShoppingCartModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userShoppingCartRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserShoppingCartModel) tableName() string {
	return m.table
}
